const AttendanceRecord = require('../models/AttendanceRecord');
const AttendanceSession = require('../models/AttendanceSession');
const User = require('../models/User');
const { asyncHandler } = require('../middleware/errorHandler');
const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');

// @desc    Export student attendance as PDF
// @route   GET /api/reports/student/:studentId/pdf
// @access  Student (self) / Faculty / Admin
const exportStudentPDF = asyncHandler(async (req, res) => {
  const student = await User.findById(req.params.studentId).populate('department', 'name');
  if (!student) return res.status(404).json({ success: false, message: 'Student not found.' });

  const records = await AttendanceRecord.find({ student: req.params.studentId })
    .populate('course', 'name code')
    .sort({ date: -1 });

  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="attendance_${student.studentProfile?.rollNo || student._id}.pdf"`);
  doc.pipe(res);

  // Header
  doc.rect(0, 0, doc.page.width, 80).fill('#4F6EF7');
  doc.fillColor('white').fontSize(22).font('Helvetica-Bold').text('AAMS — Attendance Report', 50, 20);
  doc.fontSize(11).font('Helvetica').text('Lovely Professional University, Phagwara', 50, 48);

  // Student info
  doc.fillColor('#111827').fontSize(14).font('Helvetica-Bold').text('Student Information', 50, 100);
  doc.moveTo(50, 118).lineTo(545, 118).stroke('#E5E7EB');

  const info = [
    ['Name', student.name],
    ['Roll No', student.studentProfile?.rollNo || '—'],
    ['Batch', student.studentProfile?.batch || '—'],
    ['Department', student.department?.name || '—'],
    ['Report Date', new Date().toLocaleDateString('en-IN')]
  ];

  info.forEach(([k, v], i) => {
    const y = 128 + i * 20;
    doc.fontSize(10).font('Helvetica-Bold').fillColor('#6B7280').text(k + ':', 50, y);
    doc.font('Helvetica').fillColor('#111827').text(v, 160, y);
  });

  // Summary
  const total = records.length;
  const present = records.filter(r => ['present', 'late'].includes(r.status)).length;
  const absent = records.filter(r => r.status === 'absent').length;
  const percentage = total > 0 ? Math.round((present / total) * 100) : 0;

  doc.fontSize(14).font('Helvetica-Bold').fillColor('#111827').text('Attendance Summary', 50, 240);
  doc.moveTo(50, 258).lineTo(545, 258).stroke('#E5E7EB');

  const summaryData = [
    ['Total Classes', total],
    ['Present', present],
    ['Absent', absent],
    ['Attendance %', `${percentage}%`]
  ];

  summaryData.forEach(([k, v], i) => {
    const x = 50 + i * 125;
    doc.rect(x, 268, 115, 50).fill(i === 3 ? (percentage >= 75 ? '#D1FAE5' : '#FEE2E2') : '#F9FAFB').stroke('#E5E7EB');
    doc.fillColor('#6B7280').fontSize(9).font('Helvetica').text(k, x + 8, 275);
    doc.fillColor('#111827').fontSize(16).font('Helvetica-Bold').text(String(v), x + 8, 289);
  });

  // Records Table
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#111827').text('Attendance Records', 50, 340);
  doc.moveTo(50, 358).lineTo(545, 358).stroke('#E5E7EB');

  // Table header
  doc.rect(50, 366, 495, 22).fill('#F3F4F6');
  const cols = { date: 50, course: 150, status: 320, method: 430 };
  doc.fillColor('#6B7280').fontSize(9).font('Helvetica-Bold');
  doc.text('Date', cols.date + 4, 372);
  doc.text('Course', cols.course + 4, 372);
  doc.text('Status', cols.status + 4, 372);
  doc.text('Method', cols.method + 4, 372);

  let y = 388;
  records.slice(0, 30).forEach((r, i) => {
    if (y > 750) { doc.addPage(); y = 50; }
    if (i % 2 === 0) doc.rect(50, y - 4, 495, 18).fill('#FAFAFA').stroke();

    doc.fillColor('#111827').fontSize(9).font('Helvetica');
    doc.text(new Date(r.date).toLocaleDateString('en-IN'), cols.date + 4, y);
    doc.text(r.course?.name || '—', cols.course + 4, y, { width: 160 });

    const statusColor = r.status === 'present' ? '#059669' : r.status === 'late' ? '#D97706' : '#DC2626';
    doc.fillColor(statusColor).text(r.status?.toUpperCase() || '—', cols.status + 4, y);
    doc.fillColor('#6B7280').text(r.method || '—', cols.method + 4, y);

    y += 18;
  });

  // Footer
  doc.fontSize(8).fillColor('#9CA3AF').text(
    `Generated by AAMS — ${new Date().toLocaleString('en-IN')}`,
    50, doc.page.height - 40
  );

  doc.end();
});

// @desc    Export attendance as Excel
// @route   GET /api/reports/excel
// @access  Admin / Faculty
const exportExcel = asyncHandler(async (req, res) => {
  const { courseId, startDate, endDate, deptId } = req.query;

  const filter = {};
  if (courseId) filter.course = courseId;
  if (startDate || endDate) {
    filter.date = {};
    if (startDate) filter.date.$gte = new Date(startDate);
    if (endDate) filter.date.$lte = new Date(endDate);
  }

  const records = await AttendanceRecord.find(filter)
    .populate('student', 'name email studentProfile')
    .populate('course', 'name code')
    .populate('faculty', 'name')
    .sort({ date: -1 });

  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'AAMS — LPU';
  workbook.created = new Date();

  const sheet = workbook.addWorksheet('Attendance Report', {
    pageSetup: { paperSize: 9, orientation: 'landscape' }
  });

  // Column definitions
  sheet.columns = [
    { header: 'S.No', key: 'sno', width: 6 },
    { header: 'Student Name', key: 'studentName', width: 25 },
    { header: 'Roll Number', key: 'rollNo', width: 15 },
    { header: 'Course', key: 'courseName', width: 30 },
    { header: 'Course Code', key: 'courseCode', width: 12 },
    { header: 'Date', key: 'date', width: 14 },
    { header: 'Status', key: 'status', width: 12 },
    { header: 'Check-in Time', key: 'checkIn', width: 14 },
    { header: 'Method', key: 'method', width: 12 },
    { header: 'Faculty', key: 'faculty', width: 25 },
  ];

  // Style header row
  const headerRow = sheet.getRow(1);
  headerRow.eachCell(cell => {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4F6EF7' } };
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };
    cell.alignment = { vertical: 'middle', horizontal: 'center' };
    cell.border = { bottom: { style: 'medium', color: { argb: 'FF3B5BDB' } } };
  });
  headerRow.height = 28;

  // Add data rows
  records.forEach((r, i) => {
    const row = sheet.addRow({
      sno: i + 1,
      studentName: r.student?.name || '—',
      rollNo: r.student?.studentProfile?.rollNo || '—',
      courseName: r.course?.name || '—',
      courseCode: r.course?.code || '—',
      date: new Date(r.date).toLocaleDateString('en-IN'),
      status: r.status?.toUpperCase() || '—',
      checkIn: r.checkInTime || '—',
      method: r.method || '—',
      faculty: r.faculty?.name || '—',
    });

    // Color status cell
    const statusCell = row.getCell('status');
    if (r.status === 'present') {
      statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFD1FAE5' } };
      statusCell.font = { color: { argb: 'FF059669' }, bold: true };
    } else if (r.status === 'absent') {
      statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFEE2E2' } };
      statusCell.font = { color: { argb: 'FFDC2626' }, bold: true };
    } else if (r.status === 'late') {
      statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFEF3C7' } };
      statusCell.font = { color: { argb: 'FFD97706' }, bold: true };
    }

    if (i % 2 === 0) {
      row.eachCell({ includeEmpty: true }, cell => {
        if (cell.col !== 7) {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF9FAFB' } };
        }
      });
    }

    row.alignment = { vertical: 'middle' };
    row.height = 20;
  });

  // Auto-filter
  sheet.autoFilter = { from: 'A1', to: 'J1' };

  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.setHeader('Content-Disposition', `attachment; filename="attendance_report_${Date.now()}.xlsx"`);

  await workbook.xlsx.write(res);
  res.end();
});

module.exports = { exportStudentPDF, exportExcel };
